resolver: lts-15.15
packages:

- smos
- smos-data
- smos-data-gen
- smos-cursor
- smos-cursor-gen
- smos-report
- smos-report-gen
- smos-report-cursor
- smos-report-cursor-gen
- smos-query
- smos-single
- smos-scheduler
- smos-archive
- smos-convert-org
- smos-calendar-import
- smos-docs-site
- smos-api
- smos-api-gen
- smos-server
- smos-server-gen
- smos-client
- smos-client-gen
- smos-shell
- smos-sync-client
- smos-sync-client-gen
- smos-web-server

- /home/syd/src/validity/validity
- /home/syd/src/validity/validity-aeson
- /home/syd/src/validity/validity-bytestring
- /home/syd/src/validity/validity-containers
- /home/syd/src/validity/validity-path
- /home/syd/src/validity/validity-persistent
- /home/syd/src/validity/validity-primitive
- /home/syd/src/validity/validity-scientific
- /home/syd/src/validity/validity-text
- /home/syd/src/validity/validity-time
- /home/syd/src/validity/validity-unordered-containers
- /home/syd/src/validity/validity-uuid
- /home/syd/src/validity/validity-vector
- /home/syd/src/validity/genvalidity
- /home/syd/src/validity/genvalidity-aeson
- /home/syd/src/validity/genvalidity-bytestring
- /home/syd/src/validity/genvalidity-containers
- /home/syd/src/validity/genvalidity-criterion
- /home/syd/src/validity/genvalidity-hspec
- /home/syd/src/validity/genvalidity-hspec-aeson
- /home/syd/src/validity/genvalidity-hspec-binary
- /home/syd/src/validity/genvalidity-hspec-cereal
- /home/syd/src/validity/genvalidity-hspec-hashable
- /home/syd/src/validity/genvalidity-hspec-optics
- /home/syd/src/validity/genvalidity-hspec-persistent
- /home/syd/src/validity/genvalidity-path
- /home/syd/src/validity/genvalidity-persistent
- /home/syd/src/validity/genvalidity-property
- /home/syd/src/validity/genvalidity-scientific
- /home/syd/src/validity/genvalidity-sydtest
- /home/syd/src/validity/genvalidity-sydtest-aeson
- /home/syd/src/validity/genvalidity-sydtest-lens
- /home/syd/src/validity/genvalidity-sydtest-persistent
- /home/syd/src/validity/genvalidity-text
- /home/syd/src/validity/genvalidity-time
- /home/syd/src/validity/genvalidity-unordered-containers
- /home/syd/src/validity/genvalidity-uuid
- /home/syd/src/validity/genvalidity-vector

- /home/syd/src/sydtest/sydtest-discover
- /home/syd/src/sydtest/sydtest

# These are duplicated in nix/overlay.
ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef -Wcompat

extra-deps:
- envparse-0.4.1@sha256:989902e6368532548f61de1fa245ad2b39176cddd8743b20071af519a709ce30,2842

- git: https://github.com/jtdaugherty/vty.git
  commit: 6a9c90da0e093cec1d4903924eb0f6a33be489cb

- github: ixmatus/orgmode-parse
  commit: 1bdfbfe8fb7299724a6f6a122a93b2e96dd839f8

# Calendar
- github: NorfairKing/iCalendar
  commit: 70c924ad6275ba05a514e31af1607a5b175f98ad

- mime-0.4.0.2@sha256:208947d9d1a19d08850be67ecb28c6e776db697f3bba05bd9d682e51a59f241f,983

- github: haskell-servant/servant-auth
  commit: 296de3cb69135f83f0f01169fc10f8b3a2539405
  subdirs:
    - servant-auth
    - servant-auth-client
    - servant-auth-docs
    - servant-auth-swagger
    - servant-auth-server
- servant-flatten-0.2@sha256:276896f7c5cdec5b8f8493f6205fded0cc602d050b58fdb09a6d7c85c3bb0837,1234


# Password
- github: cdepillabout/password 
  commit: 26434d4f6888faf8dc36425b20b59f0b5056d7f5
  subdirs:
    - password
    - password-instances






- github: NorfairKing/typed-uuid
  commit: ec82b82a545d06094ac355bd65a03f25f86c0a48
  subdirs:
  - typed-uuid
  - genvalidity-typed-uuid

- github: GaloisInc/sqlite
  commit: e93ee84000c1d1eedbc23036c4a20ffd07e3145f

- github: NorfairKing/mergeful
  commit: b520f251010e80748c4eea1ba7216f2594c4f760
  subdirs:
    - mergeful
    - mergeful-persistent
    - genvalidity-mergeful
  
- github: NorfairKing/pretty-relative-time
  commit: 1c0ca0e24b2a5973e5ccf4e83d24097a22bb9a4a

- github: NorfairKing/cursor-fuzzy-time
  commit: e364adc5ed04e59321aecc9a6158ca3c16f5c0bf
  subdirs:
    - cursor-fuzzy-time
    - cursor-fuzzy-time-gen
  
- github: NorfairKing/fuzzy-time
  commit: 8995f7d6dc4bb4798d13d005b47aabc45346ee3e
  subdirs:
    - fuzzy-time
    - fuzzy-time-gen

- github: NorfairKing/dirforest
  commit: 8e30537d1628ff5bcb56f99d60a9384d5e9b46ea
  subdirs:
    - dirforest
    - genvalidity-dirforest

- github: NorfairKing/cursor-dirforest
  commit: 01e862938e7950b70d0c725dbe639f6a3d369e93
  subdirs:
    - cursor-dirforest
    - cursor-dirforest-gen
    - cursor-dirforest-brick

- github: NorfairKing/cursor-brick
  commit: a7b47b03c8c5525234aaccc0c372e49a80134b9d
  subdirs:
    - cursor-brick

- github: NorfairKing/cursor
  commit: 71ec3154809e229efbf35d500ac6d1a42ae5fdc0
  subdirs:
    - cursor
    - cursor-gen

# - github: NorfairKing/validity
#   commit: c38fc635f98580548f82314504e9f8742519f94d
#   subdirs:
#   - genvalidity
#   - genvalidity-aeson
#   - genvalidity-bytestring
#   - genvalidity-containers
#   - genvalidity-criterion
#   - genvalidity-hspec
#   - genvalidity-hspec-aeson
#   - genvalidity-hspec-binary
#   - genvalidity-hspec-cereal
#   - genvalidity-hspec-hashable
#   - genvalidity-hspec-optics
#   - genvalidity-hspec-persistent
#   - genvalidity-path
#   - genvalidity-persistent
#   - genvalidity-property
#   - genvalidity-scientific
#   - genvalidity-text
#   - genvalidity-time
#   - genvalidity-unordered-containers
#   - genvalidity-uuid
#   - genvalidity-vector
#   - validity
#   - validity-aeson
#   - validity-bytestring
#   - validity-containers
#   - validity-path
#   - validity-persistent
#   - validity-primitive
#   - validity-scientific
#   - validity-text
#   - validity-time
#   - validity-unordered-containers
#   - validity-uuid
#   - validity-vector

- github: NorfairKing/yamlparse-applicative
  commit: 1d381a4cbc9736a2defc916a93cfcf8000ee7e37
  subdirs:
  - yamlparse-applicative
 
- github: NorfairKing/yesod-static-remote
  commit: f91fdbc2ac74cf8d005f536cfbbf9b4385cbbba6

- normaldistribution-1.1.0.3@sha256:2615b784c4112cbf6ffa0e2b55b76790290a9b9dff18a05d8c89aa374b213477,2160

- github: NorfairKing/haskeline
  commit: 7c6491c55741608255c2681702381ce488692d15

- github: NorfairKing/template-haskell-reload
  commit: 7111b945e3ae00ac48d905af1d925c138c334960
  subdirs:
    - template-haskell-reload

nix:
  path: [ "nixpkgs=https://github.com/NixOS/nixpkgs/archive/e3a2247046d4de66b9b193a6ab3ff040fa3da86d.tar.gz" ]
  add-gc-roots: true
  packages:
  - asciinema
  - autoconf
  - cacert
  - haskellPackages.autoexporter
  - killall
  - zlib
