name:                smos-shell
version:             0.0.0.0
github:              "NorfairKing/smos"
license:             MIT
author:              "Tom Sydney Kerckhove"
maintainer:          "syd@cs-syd.eu"
copyright:           "Copyright (c) 2020 Tom Sydney Kerckhove"

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - bytestring
  - haskeline
  - mtl
  - optparse-applicative
  - rainbow
  - smos
  - smos-query
  - smos-report
  - text
  - unliftio

executables:
  smos-shell:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - smos-shell

tests:
  smos-shell-test:
    main:                Spec.hs
    source-dirs:         test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - sydtest
    - smos-shell
