name: smos
version: 0.1.1
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2018-2020 Tom Sydney Kerckhove'
license: MIT
homepage: https://github.com/NorfairKing/smos

extra-source-files:
- test_resources/**/*

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - aeson
  - async
  - base
  - brick
  - bytestring
  - conduit
  - containers
  - contravariant
  - cursor
  - cursor-brick
  - cursor-dirforest
  - cursor-dirforest-brick
  - cursor-fuzzy-time
  - directory
  - dirforest
  - envparse
  - filelock
  - filepath
  - fuzzy-time
  - megaparsec
  - microlens
  - mtl
  - optparse-applicative
  - path
  - path-io
  - pretty-relative-time
  - pretty-show
  - process
  - resourcet
  - safe
  - smos-cursor
  - smos-data
  - smos-report
  - smos-report-cursor
  - text
  - time
  - unix
  - unliftio
  - unordered-containers
  - validity
  - validity-containers
  - validity-text
  - validity-time
  - validity-unordered-containers
  - vty
  - yaml
  - yamlparse-applicative

executables:
  smos:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -optP-Wno-nonportable-include-path # For macos
    dependencies:
    - base
    - smos

tests:
  smos-test:
    main: Main.hs
    source-dirs: test/
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - aeson
    - aeson-pretty
    - async
    - base
    - brick
    - bytestring
    - containers
    - cursor
    - cursor-dirforest
    - cursor-dirforest-gen
    - cursor-gen
    - dirforest
    - filelock
    - genvalidity
    - genvalidity-containers
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-sydtest-lens
    - genvalidity-path
    - genvalidity-text
    - genvalidity-time
    - genvalidity-unordered-containers
    - sydtest
    - megaparsec
    - path
    - path-io
    - pretty-show
    - resourcet
    - smos
    - smos-cursor
    - smos-cursor-gen
    - smos-data
    - smos-data-gen
    - smos-report
    - smos-report-cursor
    - smos-report-cursor-gen
    - smos-report-gen
    - text
    - time
    - unix
    - unliftio
    - validity
    - vty
    - yaml
    - yamlparse-applicative
